/**
 * stamp-hidden.js
 * ------------------------------------------------------------------
 * Applies the hide rules (date cutoff + manual blacklist) to the EXISTING
 * generated data WITHOUT calling Bedrock. Reads the JSON mirror produced by
 * generate-summaries.js, stamps `hidden` / `hiddenReason` onto each item,
 * and rewrites both:
 *   firebase/scripts/output/exercise-videos.json
 *   app/src/lib/exercise-videos.ts
 *
 * Use this to (re)apply hide flags quickly after editing hidden-videos.json
 * or changing the cutoff. Full regeneration (generate-summaries.js) applies
 * the same rules, so this is just a fast, free shortcut.
 *
 * USAGE (Windows cmd):
 *   node firebase\scripts\stamp-hidden.js
 *   node firebase\scripts\stamp-hidden.js --hideBefore=2025-01-01
 * ------------------------------------------------------------------
 */

"use strict";

const fs = require("fs");
const path = require("path");

const TOPICS = ["Workouts", "Nutrition", "Mindset", "Other"];
const BODY_PARTS = [
  "Chest",
  "Back",
  "Shoulders",
  "Arms",
  "Legs",
  "Core",
  "Glutes",
  "Full Body",
];

const DEFAULT_HIDE_BEFORE = "2025-01-01";

function parseArgs(argv) {
  const args = {};
  for (const raw of argv.slice(2)) {
    const m = raw.match(/^--([^=]+)=(.*)$/);
    if (m) args[m[1]] = m[2];
    else if (raw.startsWith("--")) args[raw.slice(2)] = true;
  }
  return args;
}

function parseVideoId(input) {
  if (!input || typeof input !== "string") return null;
  const s = input.trim();
  if (!s) return null;
  if (/^[A-Za-z0-9_-]{11}$/.test(s)) return s;
  try {
    const u = new URL(s);
    if (u.hostname.includes("youtu.be")) {
      const id = u.pathname.split("/").filter(Boolean)[0];
      return id && /^[A-Za-z0-9_-]{11}$/.test(id) ? id : null;
    }
    const v = u.searchParams.get("v");
    if (v && /^[A-Za-z0-9_-]{11}$/.test(v)) return v;
    const parts = u.pathname.split("/").filter(Boolean);
    const idx = parts.findIndex((p) => p === "shorts" || p === "embed");
    if (idx !== -1 && parts[idx + 1] && /^[A-Za-z0-9_-]{11}$/.test(parts[idx + 1])) {
      return parts[idx + 1];
    }
  } catch {
    /* not a URL */
  }
  return null;
}

function loadHiddenIds() {
  const p = path.join(__dirname, "hidden-videos.json");
  const ids = new Set();
  if (!fs.existsSync(p)) return ids;
  try {
    const raw = JSON.parse(fs.readFileSync(p, "utf8"));
    const list = Array.isArray(raw) ? raw : raw.hide || [];
    for (const entry of list) {
      const id = parseVideoId(entry);
      if (id) ids.add(id);
    }
  } catch (e) {
    console.warn(`  WARN: could not parse hidden-videos.json: ${e.message}`);
  }
  return ids;
}

function computeHidden(item, hideBeforeMs, manualIds) {
  if (manualIds.has(item.videoId)) return { hidden: true, hiddenReason: "manual" };
  if (hideBeforeMs && item.publishedAt) {
    const t = Date.parse(item.publishedAt);
    if (!Number.isNaN(t) && t < hideBeforeMs) return { hidden: true, hiddenReason: "date" };
  }
  return { hidden: false, hiddenReason: null };
}

function tsString(s) {
  return JSON.stringify(s == null ? "" : String(s));
}

function buildTsFile(meta, items) {
  const header = `// AUTO-GENERATED by firebase/scripts/generate-summaries.js
// Do not edit by hand (re-run the script to regenerate).
// Source channel: ${meta.channelTitle} (${meta.handle})
// Generated: ${new Date().toISOString()}

export type ExerciseTopic =
${TOPICS.map((t) => `  | ${JSON.stringify(t)}`).join("\n")};

export type BodyPart =
${BODY_PARTS.map((b) => `  | ${JSON.stringify(b)}`).join("\n")};

export type VideoFormat = "long" | "short";

export interface ExerciseVideo {
  videoId: string;
  title: string;
  summary: string;
  topic: ExerciseTopic;
  bodyParts: BodyPart[];
  format: VideoFormat;
  keywords: string[];
  durationLabel: string;
  durationSeconds: number;
  publishedAt: string | null;
  thumbnail: string;
  thumbnailFallback: string;
  url: string;
  hidden: boolean;
  hiddenReason: "date" | "manual" | null;
}

export const EXERCISE_TOPICS: ExerciseTopic[] = [
${TOPICS.map((t) => `  ${JSON.stringify(t)},`).join("\n")}
];

export const BODY_PARTS: BodyPart[] = [
${BODY_PARTS.map((b) => `  ${JSON.stringify(b)},`).join("\n")}
];

export const exerciseVideos: ExerciseVideo[] = [
`;

  const body = items
    .map((it) => {
      return `  {
    videoId: ${tsString(it.videoId)},
    title: ${tsString(it.title)},
    summary: ${tsString(it.summary)},
    topic: ${tsString(it.topic)},
    bodyParts: [${(it.bodyParts || []).map((b) => tsString(b)).join(", ")}],
    format: ${tsString(it.format)},
    keywords: [${(it.keywords || []).map((k) => tsString(k)).join(", ")}],
    durationLabel: ${tsString(it.durationLabel)},
    durationSeconds: ${it.durationSeconds || 0},
    publishedAt: ${it.publishedAt ? tsString(it.publishedAt) : "null"},
    thumbnail: ${tsString(it.thumbnail)},
    thumbnailFallback: ${tsString(it.thumbnailFallback || it.thumbnail)},
    url: ${tsString(it.url)},
    hidden: ${it.hidden ? "true" : "false"},
    hiddenReason: ${it.hiddenReason ? tsString(it.hiddenReason) : "null"},
  },`;
    })
    .join("\n");

  return `${header}${body}
];
`;
}

function main() {
  const args = parseArgs(process.argv);
  const hideBeforeStr = args.hideBefore || DEFAULT_HIDE_BEFORE;
  const hideBeforeMs = hideBeforeStr ? Date.parse(hideBeforeStr) : NaN;
  const manualIds = loadHiddenIds();

  const jsonPath = path.join(__dirname, "output", "exercise-videos.json");
  const outTsPath = path.resolve(
    process.cwd(),
    args.out || path.join("app", "src", "lib", "exercise-videos.ts")
  );

  if (!fs.existsSync(jsonPath)) {
    console.error(
      `ERROR: ${jsonPath} not found. Run generate-summaries.js first.`
    );
    process.exit(1);
  }

  const data = JSON.parse(fs.readFileSync(jsonPath, "utf8"));
  const meta = { channelTitle: data.channelTitle || "", handle: data.handle || "" };
  const items = data.items || [];

  let hiddenByDate = 0;
  let hiddenByManual = 0;
  for (const it of items) {
    const { hidden, hiddenReason } = computeHidden(it, hideBeforeMs, manualIds);
    it.hidden = hidden;
    it.hiddenReason = hiddenReason;
    if (hiddenReason === "date") hiddenByDate++;
    if (hiddenReason === "manual") hiddenByManual++;
  }

  fs.writeFileSync(jsonPath, JSON.stringify({ ...meta, items }, null, 2), "utf8");
  fs.mkdirSync(path.dirname(outTsPath), { recursive: true });
  fs.writeFileSync(outTsPath, buildTsFile(meta, items), "utf8");

  const visible = items.filter((i) => !i.hidden).length;
  console.log("Stamped hide flags.");
  console.log(`  hideBefore: ${hideBeforeStr}`);
  console.log(`  manual blacklist ids: ${manualIds.size}`);
  console.log(`  hidden by date: ${hiddenByDate}`);
  console.log(`  hidden by manual: ${hiddenByManual}`);
  console.log(`  visible: ${visible} / ${items.length}`);
  console.log(`\n  Updated: ${outTsPath}`);
  console.log(`  Updated: ${jsonPath}`);
}

main();
