import './globals.css';
import type { Metadata } from 'next';
import { AuthProvider } from '@/lib/auth-context';
import { CoachUpdatesProvider } from '@/context/CoachUpdatesContext';
import { Toaster } from '@/components/ui/toaster';
import AnalyticsListener from '@/components/AnalyticsListener';
import { SITE } from '@/lib/seo';



export const metadata: Metadata = {
  metadataBase: new URL(SITE.url),
  title: {
    default: `${SITE.name} — Personal Training & Fitness Coaching`,
    template: `%s | ${SITE.name}`,
  },
  description: SITE.description,
  keywords: [...SITE.keywords],
  applicationName: SITE.name,
  alternates: {
    canonical: '/',
  },
  openGraph: {
    type: 'website',
    siteName: SITE.name,
    title: `${SITE.name} — Personal Training & Fitness Coaching`,
    description: SITE.description,
    url: SITE.url,
    locale: SITE.locale,
  },
  twitter: {
    card: 'summary_large_image',
    title: `${SITE.name} — Personal Training & Fitness Coaching`,
    description: SITE.description,
    ...(SITE.twitterHandle ? { site: SITE.twitterHandle } : {}),
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-image-preview': 'large',
      'max-snippet': -1,
      'max-video-preview': -1,
    },
  },
  // Favicon/apple-touch icons are generated by the file conventions
  // src/app/icon.tsx (favicon) and src/app/opengraph-image.tsx (social card).
};



export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <AuthProvider>
          <CoachUpdatesProvider>
            {children}
          </CoachUpdatesProvider>
        </AuthProvider>
        <Toaster />
        <AnalyticsListener />
      </body>
    </html>
  );
}
